# After changing this file, check it on:
# http://lint.travis-ci.org/

language: python
python:
  - "2.5"
#  - "2.7"
#  - "3.2"
# command to install dependencies
before_install:
#zlib1g-dev is needed to allow PIL to uncompress the dataset.
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev zlib1g-dev zip unzip zlibc libzip-dev libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev

install:
  - "pip install -q numpy --use-mirrors"
# Use Pillow instead of PIL as it is better packaged
  - "pip install -q Pillow --use-mirrors"
#If we don't install numpy before SciPy 0.10.1, the SciPy installations fails.
#  - "pip install -q scipy --use-mirrors"
  - "pip install --no-deps git+git://github.com/Theano/Theano.git"
env:
  - PART="test.py:test_logistic_sgd test.py:test_logistic_cg test.py:test_mlp"
  - PART="test.py:test_convolutional_mlp test.py:test_dA"
  - PART="test.py:test_SdA"
  - PART="test.py:test_dbn"
  - PART="test.py:test_rbm"
  - PART="-e test.py"

#569.882s   #10     code.test.test_rbm OK
#298.992s   #9      code.test.test_dbn OK
#268.901s   #8      code.test.test_SdA OK
#67.292s    #7      code.test.test_dA OK
#27.485s    #5      code.test.test_mlp OK
#26.204s    #6      code.test.test_convolutional_mlp OK
#14.676s    #4      code.test.test_logistic_cg OK
#10.66s     #3      code.test.test_logistic_sgd OK
#5.795s     #1      code.mcrbm.test_hmc.test_hmc OK
#0.0s       #2      code.mcrbm.test_mcrbm.test_reproduce_ranzato_hinton_2010 FAILED TEST

script:
  - cd data
  - ./download.sh
  - ls
  - cd ../code
  - pwd
  - ls
  - export THEANO_FLAGS=warn.ignore_bug_before=all,on_opt_error=raise,on_shape_error=raise
  - python --version
  - nosetests $PART

